### ISSUE TITLE
Code not displaying

### ISSUE THREAD

**Issue by matackett** [matackett/learning-r#11]
@jacobfhsmith 

The code is hidden in the Into the Tidyverse tutorial. Can you please take a look at it and update it? Just tag me in the issue once the tutorial is updated and I'll deploy the new version. 
Thanks!

**Comment by jacobfhsmith** [comment]
I uploaded new versions w/code set to display in that Github folder-- is there another step to get it to display on the website?

**Comment by matackett** [comment]
I redeployed it, so it's good to go now. thanks!
