### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by joan-combs-durso** [matackett/learning-r#6]
@matackett 

The images are not rendering for me in Chrome, while on the vpn, on this page:
http://knight.stat.duke.edu:3939/basics-r/#section-the-rstudio-interface-getting-started

![Screen Shot 2020-08-12 at 7 45 06 PM](https://user-images.githubusercontent.com/58050151/90079124-fcc27000-dcd4-11ea-8919-8f9889191464.png)

**Comment by matackett** [comment]
@jacobfhsmith @joan-combs-durso 

Fixed! the new tutorial is online under http://knight.stat.duke.edu:3939/r-basics/
