### ISSUE TITLE
inference tutorials updates

### ISSUE THREAD

**Issue by rdeisinger** [matackett/learning-r#7]
@matackett 

Pushed updates to inference tutorials.

**Bootstrapping with Infer**
- fixed typo in introduction (exchange not exchange)
- fixed typo in introduction (verizon.csv not Verizon.csv)
- fixed setup chunk
- allowed retries on quiz questions
- combined “Your turn” exercise code chunks to avoid student confusion
- In “Your turn” question 2 “Use the code chunk…” instead of “Fill in the blanks…”
- removed earlier boot_dist to avoid confusion in answering “Your turn” questions

**CLT-Based Inference with Infer**
- fixed setup chunk
- Combined exercise code chunks in “Your Turn” questions 1 and 2 to avoid student confusion
- fixed typo: CLT based null null distribution

**Sim-Based Inference with Infer**
- fixed setup chunk
- added set.seed for consistent results
- fixed typo: “you can do this in using”

**Comment by matackett** [comment]
@rdeisinger 

thanks! I redeployed the updated apps.
